Add missing checkdepends vulkan-headers
meson test fails without vulkan-headers:

```
[1/2] Compiling C object vulkanprog.p/vulkanprog.c.o
FAILED: vulkanprog.p/vulkanprog.c.o 
cc -Ivulkanprog.p -I. '-I../test cases/frameworks/18 vulkan' -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -MD -MQ vulkanprog.p/vulkanprog.c.o -MF vulkanprog.p/vulkanprog.c.o.d -o vulkanprog.p/vulkanprog.c.o -c '../test cases/frameworks/18 vulkan/vulkanprog.c'
../test cases/frameworks/18 vulkan/vulkanprog.c:1:10: fatal error: vulkan/vulkan.h: No such file or directory
    1 | #include <vulkan/vulkan.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```